kind: Service
apiVersion: v1
metadata:
  name: osrm
  labels:
    app: osrm
spec:
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: 5000
  selector:
    app: osrm
    version: "$VERSION"